// angular/src/components/spacer/index.ts
import { Component, Input } from "@angular/core";

@Component({
  selector: "app-spacer",
  host: { style: "display: contents" },
  templateUrl: "./template.html",
})
export default class Spacer {
  @Input() height: string = "small";
  readonly heights: Record<string, string> = {
    small: "h-8",
    medium: "h-12",
    large: "h-16",
    extra_large: "h-24",
  };
}

// nuxt/app/components/spacer/index.vue
<script setup lang="ts">
const props = withDefaults(defineProps<{ height: 'small' | 'medium' | 'large' | 'extra_large' }>(), { height: 'small' })
const heights = { small: 'h-8', medium: 'h-12', large: 'h-16', extra_large: 'h-24' }
</script>

<template><div :class="heights[props.height]" aria-hidden="true" /></template>
