// angular/src/components/hero/index.ts
import { Component, Input } from "@angular/core";
import { CanvasSlot, CanvasMarkup } from "@drupal-canvas/headless-angular";
import Heading from "../heading";

@Component({
  selector: "app-hero",
  imports: [CanvasSlot, CanvasMarkup, Heading],
  host: { style: "display: contents" },
  templateUrl: "./template.html",
})
export default class Hero {
  @Input() image?: {
    src: string;
    alt?: string;
    width?: number;
    height?: number;
  };
  @Input() layout: string = "left_aligned";
  @Input() columnWidths: string = "50_50";
  @Input() preHeading: string = "";
  @Input() heading: string = "";
  @Input() headingElement: string = "h2";
  @Input() headingSize: string = "large";
  @Input() text: string = "";
  @Input() textColor: string = "dark";
  @Input() textShadow: string = "medium";
  @Input() backgroundImage?: {
    src: string;
    alt?: string;
    width?: number;
    height?: number;
  };
  @Input() darkenImage: boolean = false;
  readonly widths: Record<string, string[]> = {
    "33_66": ["md:w-1/3", "md:w-2/3"],
    "50_50": ["md:w-1/2", "md:w-1/2"],
    "66_33": ["md:w-2/3", "md:w-1/3"],
  };
  readonly layouts: Record<string, string> = {
    text_image: "flex-col md:flex-row",
    image_text: "flex-col md:flex-row-reverse",
  };
  readonly shadows: Record<string, string> = {
    light: "text-shadow-sm",
    medium: "text-shadow-md",
    heavy: "text-shadow-lg",
  };
}

// nuxt/app/components/hero/index.vue
<script setup lang="ts">
import TwoColumnText from '@/ui/TwoColumnText.vue'

interface Image { src: string, alt?: string }
const props = withDefaults(defineProps<{
  backgroundImage: Image, layout: 'left_aligned' | 'centered', preHeading?: string, headingElement?: string,
  headingSize: 'extra_large' | 'large' | 'medium' | 'small', heading?: string, text?: string, textColor: 'dark' | 'light',
  darkenImage?: boolean,
}>(), { layout: 'left_aligned', headingElement: 'h2', headingSize: 'large', textColor: 'dark', darkenImage: false })
const nebulaLayout = props.layout as unknown as 'text_image'
</script>

<template>
  <div class="flex min-h-[672px] w-full justify-start bg-cover bg-center bg-no-repeat" :style="props.backgroundImage?.src ? { backgroundImage: `url(${props.backgroundImage.src})` } : undefined">
    <div :class="['align-center h-full w-full px-8 py-16', props.darkenImage && 'backdrop-brightness-75']">
      <TwoColumnText
        :layout="nebulaLayout"
        :pre-heading="props.preHeading"
        :heading="props.heading"
        :heading-element="props.headingElement"
        :heading-size="props.headingSize"
        :text="props.text"
        :text-color="props.textColor"
        text-shadow="medium"
      >
        <template #buttons><slot name="buttons" /></template>
      </TwoColumnText>
    </div>
  </div>
</template>
